# Generated by Django 5.2 on 2025-04-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('base_image', models.ImageField(upload_to='interactive_sheets/images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('corrected', 'Corrected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expiration_date', models.DateTimeField()),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_sheets', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
