# Generated by Django 5.2 on 2025-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivesheet',
            name='interactive_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
