# Generated by Django 5.2 on 2025-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sheets', '0002_interactivesheet_interactive_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivesheet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('corrected', 'Corrected'), ('expired', 'Expired'), ('assigned', 'Assigned')], default='pending', max_length=10),
        ),
    ]
