# Generated by Django 5.2 on 2025-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sheets', '0004_sheetsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsubmission',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('corregida', 'Corregida')], default='pendiente', max_length=20),
        ),
    ]
