# Generated by Django 5.2 on 2025-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='prueba', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname_1',
            field=models.CharField(default='prueba', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
