# Generated by Django 5.2 on 2025-05-15 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_sheets', '0005_sheetsubmission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Clase')),
                ('class_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Código de Clase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('sheets', models.ManyToManyField(blank=True, related_name='classrooms', to='interactive_sheets.interactivesheet', verbose_name='Fichas Asignadas')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
        ),
    ]
